# Generated by Django 3.1.4 on 2020-12-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
