# Generated by Django 3.1.4 on 2020-12-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
