# Generated by Django 3.1.4 on 2020-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(upload_to='foto/%Y/%m/%d'),
        ),
    ]
