# Generated by Django 3.1.4 on 2020-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_auto_20201225_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='foto/%Y/%m/%d'),
        ),
    ]
